Name:           ros-lunar-cartographer-rviz
Version:        0.2.0
Release:        0%{?dist}
Summary:        ROS cartographer_rviz package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://github.com/googlecartographer/cartographer_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       qt5-qtbase
Requires:       qt5-qtbase-devel
Requires:       qt5-qtbase-gui
Requires:       ros-lunar-cartographer
Requires:       ros-lunar-cartographer-ros
Requires:       ros-lunar-cartographer-ros-msgs
Requires:       ros-lunar-eigen-conversions
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-roslib
Requires:       ros-lunar-rviz
BuildRequires:  gcc-c++
BuildRequires:  glibc-devel
BuildRequires:  glibc-static
BuildRequires:  libstdc++-devel
BuildRequires:  libstdc++-static
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtbase-gui
BuildRequires:  ros-lunar-cartographer
BuildRequires:  ros-lunar-cartographer-ros
BuildRequires:  ros-lunar-cartographer-ros-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-eigen-conversions
BuildRequires:  ros-lunar-message-runtime
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roslib
BuildRequires:  ros-lunar-rviz

%description
Cartographer is a system that provides real-time simultaneous localization and
mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.
This package provides Cartographer's RViz integration.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Mar 30 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-0
- Autogenerated by Bloom

