Name:           ros-lunar-cartographer-ros-msgs
Version:        0.2.0
Release:        3%{?dist}
Summary:        ROS cartographer_ros_msgs package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://github.com/googlecartographer/cartographer_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-message-generation

%description
ROS messages for the cartographer_ros package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sat Mar 31 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-3
- Autogenerated by Bloom

* Fri Mar 30 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-2
- Autogenerated by Bloom

* Fri Mar 30 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-1
- Autogenerated by Bloom

* Fri Mar 30 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-0
- Autogenerated by Bloom

