Name:           ros-lunar-cartographer-ros
Version:        0.2.0
Release:        1%{?dist}
Summary:        ROS cartographer_ros package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://github.com/googlecartographer/cartographer_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       gflags-devel
Requires:       glog-devel
Requires:       pcl-devel
Requires:       ros-lunar-cartographer
Requires:       ros-lunar-cartographer-ros-msgs
Requires:       ros-lunar-eigen-conversions
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-nav-msgs
Requires:       ros-lunar-pcl-conversions
Requires:       ros-lunar-robot-state-publisher
Requires:       ros-lunar-rosbag
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-roslaunch
Requires:       ros-lunar-roslib
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-tf2
Requires:       ros-lunar-tf2-eigen
Requires:       ros-lunar-tf2-ros
Requires:       ros-lunar-urdf
Requires:       ros-lunar-visualization-msgs
Requires:       yaml-cpp-devel
BuildRequires:  gcc-c++
BuildRequires:  gflags-devel
BuildRequires:  glibc-devel
BuildRequires:  glibc-static
BuildRequires:  glog-devel
BuildRequires:  gmock-devel
BuildRequires:  libstdc++-devel
BuildRequires:  libstdc++-static
BuildRequires:  pcl-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  python-sphinx
BuildRequires:  ros-lunar-cartographer
BuildRequires:  ros-lunar-cartographer-ros-msgs
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-eigen-conversions
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-message-runtime
BuildRequires:  ros-lunar-nav-msgs
BuildRequires:  ros-lunar-pcl-conversions
BuildRequires:  ros-lunar-robot-state-publisher
BuildRequires:  ros-lunar-rosbag
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roslaunch
BuildRequires:  ros-lunar-roslib
BuildRequires:  ros-lunar-rosunit
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-tf2
BuildRequires:  ros-lunar-tf2-eigen
BuildRequires:  ros-lunar-tf2-ros
BuildRequires:  ros-lunar-urdf
BuildRequires:  ros-lunar-visualization-msgs
BuildRequires:  yaml-cpp-devel

%description
Cartographer is a system that provides real-time simultaneous localization and
mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.
This package provides Cartographer's ROS integration.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Fri Mar 30 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-1
- Autogenerated by Bloom

* Fri Mar 30 2018 Mikael Arguedas <mikael@osrfoundation.org> - 0.2.0-0
- Autogenerated by Bloom

