Name:           ros-melodic-cartographer-ros
Version:        1.0.0
Release:        1%{?dist}
Summary:        ROS cartographer_ros package

Group:          Development/Libraries
License:        Apache 2.0
URL:            https://github.com/googlecartographer/cartographer_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       gflags-devel
Requires:       glog-devel
Requires:       pcl-devel
Requires:       ros-melodic-cartographer >= 1.0.0
Requires:       ros-melodic-cartographer-ros-msgs >= 1.0.0
Requires:       ros-melodic-eigen-conversions
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-pcl-conversions
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roslaunch
Requires:       ros-melodic-roslib
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf2
Requires:       ros-melodic-tf2-eigen
Requires:       ros-melodic-tf2-ros
Requires:       ros-melodic-urdf
Requires:       ros-melodic-visualization-msgs
BuildRequires:  gcc-c++
BuildRequires:  gflags-devel
BuildRequires:  glibc-devel
BuildRequires:  glibc-static
BuildRequires:  glog-devel
BuildRequires:  gmock-devel
BuildRequires:  libstdc++-devel
BuildRequires:  libstdc++-static
BuildRequires:  pcl-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  python-sphinx
BuildRequires:  ros-melodic-cartographer >= 1.0.0
BuildRequires:  ros-melodic-cartographer-ros-msgs >= 1.0.0
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-eigen-conversions
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-message-runtime
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-pcl-conversions
BuildRequires:  ros-melodic-robot-state-publisher
BuildRequires:  ros-melodic-rosbag
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslaunch
BuildRequires:  ros-melodic-roslib
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf2
BuildRequires:  ros-melodic-tf2-eigen
BuildRequires:  ros-melodic-tf2-ros
BuildRequires:  ros-melodic-urdf
BuildRequires:  ros-melodic-visualization-msgs

%description
Cartographer is a system that provides real-time simultaneous localization and
mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.
This package provides Cartographer's ROS integration.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jun 08 2018 The Cartographer Authors <cartographer-owners@googlegroups.com> - 1.0.0-1
- Autogenerated by Bloom

* Fri Jun 01 2018 The Cartographer Authors <cartographer-owners@googlegroups.com> - 1.0.0-0
- Autogenerated by Bloom

* Wed May 02 2018 The Cartographer Owners <cartographer-owners@googlegroups.com> - 0.3.0-0
- Autogenerated by Bloom

